
  <!-- ********************** --> 
  <!--      C O N T E N T     --> 
  <!-- ********************** --> 
  <div id="content" class="container_12">
  
    <div id="shopping_cart" class="grid_12">

      
        <table class="s_table_1" width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <th width="200">Название</th>
            <th width="200">Картинка</th>
          </tr>
          <tr><td><p><?php echo $this->product['title']?></p></td>
          <td><img style="margin: 0 auto;"width="200px" height="200px"src="/images/<?php echo $this->product['small_image']?>"/></td></tr>
          
          
          </table>
          
        <br />
        <div class="clear"></div>
        <br />
        <?php  $url = $this->url(array('controller' => 'index', 'action' => 'oldoffer', 'module' => 'admin' , 'id' => $this->product['id']),'default');?>
        <a class="s_button_1 s_main_color_bgr" href="<?php echo $url?>"><span class="s_text">Подтвердить</span></a>
     
      </table>
      
        <br />
        
      
      

    </div>

    <div class="clear"></div>
    <br />
    <br />
    
  </div>
  <!-- end of content --> 
  
  