<div id="special_home" class="grid_12">
      <h2 class="s_title_1"><span class="s_main_color">Ваша корзина</span></h2>
      <div class="clear"></div>
  
  
  <!-- ********************** --> 
  <!--      C O N T E N T     --> 
  <!-- ********************** --> 
  <div id="content" class="container_12">
  
    <div id="shopping_cart" class="grid_12">

      
        <table class="s_table_1" width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <th width="100">Название</th>
            <th width="60">Изображение</th>
            <th width="100">Описание</th>
            <th width="100">Действия</th>
            <th>Quantity</th>
            <th>Unit Price</th>
            <th>Total</th>
          </tr>
          <?php if (count($this->products)>0):?>
          <?php foreach($this->products as $product ):?>
          <tr class="even">
          <td valign="middle"><a href="product.html"><strong><?php echo $product['title'] ?></strong></a></td>
            <td valign="middle"><a href="product.html"><img src="images/<?php echo $product['small_image']?>" width="160" height="160" alt="Panasonic Lumix" /></a></td>
            <td valign="middle"><?php echo $product['discription'];?></td>
            <td valign="middle">
            <?php $url = $this->url(array('controller' => 'cart', 'action' => 'plus', 'id' => $product['id']), 'default');?>
                                <a href="<?php echo $url; ?>"><img src="<?php echo "/images/navigation/plus_icon"?>" align="bottom" width="30"/> </a>
            <?php $url = $this->url(array('controller' => 'cart', 'action' => 'minus', 'id' => $product['id']), 'default');?>
                                <a href="<?php echo $url;?>"><img src="<?php echo "/images/navigation/minus_icon"?>" align="bottom" width="30"/> </a>
            <?php $url = $this->url(array('controller' => 'cart', 'action' => 'remove', 'id' => $product['id']), 'default');?>
                                <a href="<?php  echo $url;?>"><img src="<?php echo "/images/navigation/remove_icon"?>" align="bottom" width="30"/> </a>
            </td>
            <td valign="middle"><?php echo $product['count']?></td>
            <td valign="middle"><?php echo $product['price']?><span class="s_currency s_after"> руб</span></td>
            <td valign="middle"><?php echo $product['price'] * $product['count'];?><span class="s_currency s_after"> рулблей</span></td>
          </tr>
          <?php endforeach;?>
          
        </table>
        <br />
        <p  class="s_total s_secondary_color last">Total:
        <?php
        $totalsum = 0 ;
         foreach($this->products as $product){
            $totalsum += ($product['price'] * $product['count']);
         }
         echo $totalsum;
        ?>
        <span class="s_currency s_after">рублей</span></p>
        <div class="clear"></div>
        <br />
        <?php  $url = $this->url(array('controller' => 'cart', 'action' => 'make-order'),'default');?>
        <a class="s_button_1 s_main_color_bgr" href="<?php echo $url?>"><span class="s_text">Оформить заказ</span></a>
      <?php else:?>
      </table>
      Ваша корзина пуста
        <br />
        
      <?php endif; ?>
      

    </div>

    <div class="clear"></div>
    <br />
    <br />
    
  </div>
  <!-- end of content --> 
  
  